### ISSUE TITLE
Date difference - Hired on

### ISSUE THREAD

**Issue by timcwilson** [officelifehq/officelife#1009]
Hiring date information on the employee edit screen is set as 1/1/2020.
However on the employee screen it shows as Hired on Jan 02, 2020.
Not overly important to me, but it will be important to someone :-).

**Comment by djaiss** [comment]
Thanks for the bug report @timcwilson.

You might be right - dates on the profile page took into account the timezones, which shouldn't actually, as those dates shouldn't be affected by timezones.

I'll fix it in a couple of minutes.
