### ISSUE TITLE
Permissions Error using OpenShift

### ISSUE THREAD

**Issue by ChaosKnign** [officelifehq/officelife#1026]
Getting an error during Storage directory creation when deploying container to IBM's OpenShift service.

```
chown: changing ownership of '/var/www/html/storage/app/public': Operation not permitted
chown: changing ownership of '/var/www/html/storage/app': Operation not permitted
chown: changing ownership of '/var/www/html/storage/framework/cache': Operation not permitted
chown: changing ownership of '/var/www/html/storage/framework/sessions': Operation not permitted
chown: changing ownership of '/var/www/html/storage/framework/views': Operation not permitted
chown: changing ownership of '/var/www/html/storage/framework': Operation not permitted
chown: changing ownership of '/var/www/html/storage/logs': Operation not permitted
chown: changing ownership of '/var/www/html/storage': Operation not permitted
```

OpenShift uses additional security constraints when running a container. Unlike Docker or Kubernetes, OpenShift does not run containers using the root user. Per RedHat:

> By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.
> 
> For an image to support running as an arbitrary user, directories and files that may be written to by processes in the image should be owned by the root group and be read/writable by that group. Files to be executed should also have group execute permissions.

**Comment by asbiin** [comment]
This is not a bug in OfficeLife. It relates to the way you install the application.
Unfortunately, I have 0 knowledge on Openshift, and we will not make support on it.

OfficeLife is a Laravel application. maybe you may find some help on the Internet about how to deploy a Laravel application on Openshift?

**Comment by ChaosKnign** [comment]
Thanks for the reply! =D

I can see it not being a "bug" per se. It's more related to how the docker container is built out, where some changes are made after the container is built. Openshift is just picky when you start up a container and it keeps building, it doesn't like that. Openshift integrates an s2i runtime for PHP, though. 

Any way to build out the directory and permissions structure before building the image? So that all you need to do is pass ENV through the Dockerfile for DBs, admin, pass, etc?

Sorry, this thread is not the place to discuss this. xD I'll take this to your Discussion section. Thanks again for taking the time to answer!
