### ISSUE TITLE
Birthdate is required in the Edit personal information tab; this is problematic since we don't know birthdates of contractors

### ISSUE THREAD

**Issue by OrinSafko** [officelifehq/officelife#1065]
We have a contractor that we've hired to help us with a variety of tasks. I've added them into OfficeLife. They are an external employee. It is not common to know the birthdates of contractors and it would not be appropriate to ask a contractor's birthdate since this information isn't relevant to the business transaction.

Can you please change this so that birthdate is not a required field in the Edit personal information tab of the profile screen?

**Comment by djaiss** [comment]
I didn't think of this use-case, but it makes sense, especially since we can indicate that an employee can be external.

We'll change this limitation.

**Comment by OrinSafko** [comment]
Great! Thanks @djaiss.
