### ISSUE TITLE
Long task titles hang over the left side of the task box

### ISSUE THREAD

**Issue by OrinSafko** [officelifehq/officelife#1067]
![image](https://user-images.githubusercontent.com/44587173/121958030-2e5efa00-cd31-11eb-9da0-8494b3cbcf21.png)

Image attached to show the issue.

**Comment by djaiss** [comment]
Sorry for the long delay, been working super, super hard on the recruiting aspect of OfficeLife which is almost finished and is the biggest feature of the project yet.

The linked PR should fix this issue.
