### ISSUE TITLE
Software management - when editing a piece of software, the Order number is blanked out

### ISSUE THREAD

**Issue by OrinSafko** [officelifehq/officelife#1073]
I've been adding order numbers to software. However, when I go to edit a piece of software that has an order number on it, the order number is blank in the edit screen. That means that when I save my changes, the order number disappears.

The only way around this is to copy my order number before I edit the piece of software, make the edits I need to make, then paste the order number into the order number field again before I save. If I don't do that the order number is lost.

**Comment by djaiss** [comment]
Thansk @OrinSafko for all these bug reports!

**Comment by OrinSafko** [comment]
> Thansk @OrinSafko for all these bug reports!

Happy to help!
