### ISSUE TITLE
Unable to add notes to a One on One

### ISSUE THREAD

**Issue by OrinSafko** [officelifehq/officelife#1101]
I just had my first one on one. I typed in some notes, but when I click the "Add" button, the notes aren't actually added to the one on one. This only happens with longer notes. Please see the video demonstration below.

https://share.sendspark.com/view/vofnnzvi7ophwd9e

I know that some fields in OfficeLife are limited to 255 characters intentionally. I hope that the one on one notes section is not limited to 255 characters since I may have lengthy notes that need to be added into this section. I could not find a limitation for this field mentioned in the documentation.

**Comment by djaiss** [comment]
🤦  that's my bad. Let me fix that.

**Comment by djaiss** [comment]
It is indeed limited to 255 characters and this is probably a mistake.

**Comment by djaiss** [comment]
Ok after investigation, there are several cases:
- the talking points and action items are limited to 255 characters.
- the notes themselves are limited to 65 555 characters, but the front end currently limits them to 255. I'll remove this limitation.

@OrinSafko do you think the talking points and action items should be lengthier too?

**Comment by OrinSafko** [comment]
> Ok after investigation, there are several cases:
> 
> * the talking points and action items are limited to 255 characters.
> * the notes themselves are limited to 65 555 characters, but the front end currently limits them to 255. I'll remove this limitation.
> 
> @OrinSafko do you think the talking points and action items should be lengthier too?

@djaiss thanks for resolving this! I was able to add my notes from my one on one yesterday.

Regarding length of talking points and action items. I don't think that these areas will be used for lengthy points like the notes section.

However, if it's easy to remove the limitation and there are no negative consequences, there may be OfficeLife users in the future that don't want a limitation. What are the cons to removing the limitation?
