### ISSUE TITLE
demo.officelife.io is down?

### ISSUE THREAD

**Issue by DavidePrincipi** [officelifehq/officelife#1134]
Since yesterday I get a blank page after login

https://demo.officelife.io/1/welcome

Here 500

https://demo.officelife.io/1/dashboard/manager

![image](https://user-images.githubusercontent.com/2920838/123216808-37d32980-d4ca-11eb-909a-7b8543ecf12d.png)

**Comment by djaiss** [comment]
@DavidePrincipi thanks so much for bringing that to our attention! We didn't see that there was an error on this server, we haven't implemented monitoring on the demo instance yet.
I'll check immediately what's going on, thanks for letting us know!

**Comment by djaiss** [comment]
It's fixed, but we'll monitor that closely now. Thanks again!!

**Comment by DavidePrincipi** [comment]
Thank you for your fixing it! 

I reopen this issue because this morning the error page appears again after log in

![image](https://user-images.githubusercontent.com/2920838/123384624-ec398200-d594-11eb-9a14-e1c4e9856f7c.png)

**Comment by djaiss** [comment]
Yeah I don't know how it's possible. We have setup the instance so it resets every hour but for some unknown reasons, the Company table is emptied. I've disabled this for now until I understand why. Thanks again for your patience.
