### ISSUE TITLE
Heroku Deployment & Populate account with fake data Failing

### ISSUE THREAD

**Issue by nikhiljain0** [officelifehq/officelife#1209]
Heroku app URL: https://nj-office-lite.herokuapp.com/
<img width="1792" alt="Screenshot 2021-07-25 at 1 15 14 PM" src="https://user-images.githubusercontent.com/82934775/126891690-316a9b75-ccf8-4f6c-a1d7-7c896b94d0e1.png">

Have set up the Heroku Scheduler.

Using Heroku CLI, I tried to run `php artisan setup:dummyaccount`, but for some reason it's failing, attaching the error screenshot

<img width="1075" alt="Screenshot 2021-07-25 at 1 18 55 PM" src="https://user-images.githubusercontent.com/82934775/126891779-f06e4aad-6a8c-43b2-ac4c-774024626063.png">

I have deployed this app using the Heroku Button on 25th July 2021 12:53PM IST
How do I fix it?

**Comment by djaiss** [comment]
You might find an answer here: https://github.com/officelifehq/officelife/issues/788

**Comment by djaiss** [comment]
Closing. Feel free to reopen if this didn't answer your question.
