### ISSUE TITLE
Expense total is limited 1.000.000

### ISSUE THREAD

**Issue by thanhpd-teko** [officelifehq/officelife#1301]
Hi, I see that when I log new expense the total is limited by 1.000.000. However in our country this number is really small (VND)
Please help to increase this limitation.
![image](https://user-images.githubusercontent.com/47600586/132125487-5e986a29-3f7e-4c2e-9203-9af5ae2a02f2.png)

**Comment by djaiss** [comment]
@thanhpd-teko thanks for the tip, I didn't know. I'll remove the limit.
