### ISSUE TITLE
[Feature Request] Provide alternative backend for file storage

### ISSUE THREAD

**Issue by meichthys** [officelifehq/officelife#1420]
Currently it seems like we have one option for file storage (Uploadcare).
In order to stay in control of our own data it would be nice to be able to use an alternate (like Nextcloud) as a storage backend.

**Comment by djaiss** [comment]
I've discussed it here: https://github.com/officelifehq/officelife/discussions/745

I know it's really not ideal, but it allowed me to iterate way faster, as managing uploads is such a pain in the **s generally.

**Comment by meichthys** [comment]
Completely makes sense. A good future improvement for employers like mine that have policies to keep all data locally.
Feel free to close this for now.

**Comment by djaiss** [comment]
I totally agree with you. For sure, as soon as I find the time, I should work on supporting a different provider. We've done it for [Monica](https://github.com/monicahq/monica), so we'll do it too here.

**Comment by djaiss** [comment]
Are you using OfficeLife at work already?

**Comment by meichthys** [comment]
We are not currently using it but have begun testing it. 👍
[Nextcloud File-Drop](https://nextcloud.com/file-drop/) would be an ideal solution for us if that could be a viable alternative.
