### ISSUE TITLE
demo hosting 500 internal error

### ISSUE THREAD

**Issue by chaniago123456** [officelifehq/officelife#1443]
Demo website running into 500 internal error. Idk if it may be discontinued or not, but it would be nice if we can download the demo database, as it has so many nice examples we can browse at localhost on our own server.

OfficeLife and Monica are simply the best way people can learn Laravel + Vue + Blade programming. If I were you, I would write a complete guide book and earn royalty for life. They are so easy to understand and help me learn coding.

Demo Mysql DB (e.g. officelife.sql) would be nice. Thanks in advance!

**Comment by djaiss** [comment]
Let me know if that helped! I'll close the issue in the meantime.

**Comment by chaniago123456** [comment]
merci beaucoup! many thnx, it works!

As I said, perhaps considering writing a complete and comprehensive book (O'reilly etc) or e-book in Laravel+Vue+Inertia programming. To be honest, I've been browsing google and duckduckgo since 2018 and couldn't find live demo or examples as good as OfficeLife or Monica. It is so well structured and people can follow the live features easily. I am not using either Monica or OfficeLife for relationship nor office journal, only to learn Laravel programming, and I think many beginners would appreciate your work very much!

p.s. : I just lost $4K trading sh*tcoin due to scam on BSC, next time when I can get my money back, I'll consider to donate some to your patreon. :)

**Comment by djaiss** [comment]
That's very nice of you to say.

Isn't the codebase too complex? I sometimes wonder if we overengineer stuff, especially with the ViewHelpers in OfficeLife etc...
