### ISSUE TITLE
not able to checkout demo website

### ISSUE THREAD

**Issue by narasimhajupally** [officelifehq/officelife#1462]
it is asking for two factor authentication as I login with demo account given below.

Email: admin@admin.com
Password: admin123

**Comment by vlood** [comment]
Same for me. Seems like they forgot that they a rolling out a feature to a site that needs to be accessible to everyone :)

**Comment by djaiss** [comment]
Yep. I will revert that right away. Thanks for telling us :-D

**Comment by djaiss** [comment]
It's fixed, finally.
