### ISSUE TITLE
What the font

### ISSUE THREAD

**Issue by elephantux** [officelifehq/officelife#1473]
Sorry for the off-topic, but I'm very curious about the font used in the logo.

![TLogo](https://www.officelife.io/officelife-logo.svg)

**Comment by djaiss** [comment]
😃 
It's a custom font I made by hand with Paint.

**Comment by djaiss** [comment]
Just kidding 😃 it's called Bhavuka and is part of Figma.

**Comment by djaiss** [comment]
It's not available on google font though
