### ISSUE TITLE
Removal of dependabot

### ISSUE THREAD

**Issue by djaiss** [officelifehq/officelife#380]
Dependabot creates a lot of noise in the commit logs.

Could we, instead, schedule a github action that would do a `composer update` and `yarn` every week, and commit this with a simple commit message, instead of 12 commits? @asbiin what do you think?

**Comment by asbiin** [comment]
I don't think that's recommended neither feasible.
Changing dependencies can lead to test fails, and diagnosis of fails would be very hard if multiple upgrade are mixed in a same commit/PR.
Example with these PR:
- #415 : I had to fix a value that has changed (obsolete)
- #428 : phpunit upgrade will require some adaptation
- #429 : psalm upgrade advice new (relevant) fixes

I understand you see that as "noise", but on the other hand it guarantee the stability of the product. (you just have to made more commits yourself!)
