### ISSUE TITLE
Improve CI build times

### ISSUE THREAD

**Issue by djaiss** [officelifehq/officelife#475]
The `SetupDummyAccount` command takes a lot of time. I strongly believe that we should keep testing it to make sure it works, as it will be used by all the developers that want dummy data in their accounts to test and try the product.

Also, we need it ourselves to populate our default test account that we will provide at launch.

However, it’s not efficient to run it alongisde all the other tests.

I propose the following strategy:

- in `phpunit.xml`, remove the `./tests/Integration` from running.
- create another `phpunit.xml` that will run only the `./tests/Integration` files and use it in a separate `build.yml` file

That will allow us to run it in parallel of all the other tests, so that would help.

What do you think @asbiin ?

**Comment by asbiin** [comment]
I agree with the needs of accelerate build/test times.

However, I can found another solution that is easier.
In a nutschell:
- keep the ability to run tests on your desktop at once
- run tests in parallel in the CI
- improve `SetupDummyAccount` test, and other slow tests

It must also be efficient: we cannot spawn too many vm agents in parallel. To be tested...

**Comment by djaiss** [comment]
Can this be closed?

**Comment by asbiin** [comment]
yes
