### ISSUE TITLE
Population dummyacount fails on missing class Faker\Factory

### ISSUE THREAD

**Issue by meijbaard** [officelifehq/officelife#722]
I've installed the system in to an heroku instance. While deploying works perfect, setting up the dummyaccount following the installation guide on docs.officelife.io there is an error when running the command:

_php artisan setup:dummyaccount_

![Schermafbeelding 2021-04-07 om 09 24 01](https://user-images.githubusercontent.com/58352861/113826924-3c612f00-9772-11eb-9175-325b9d96e859.png)

Is there anything missing? Or did I miss a step in the heroku deploy?

**Comment by djaiss** [comment]
You are officially the first person external of the project to post an issue here! I didn't expect it at all 😄 

Thanks for checking out the project.

Did `composer install` work well?

**Comment by djaiss** [comment]
Any idea @asbiin ?

**Comment by asbiin** [comment]
I think heroku installation is made for production installation, and it does not install dev composer packages - which includes faker.
Try installing all composer packages (composer install) then retry.

**Comment by meijbaard** [comment]
I shall retry this; I also had this issue on my own linux machine (Pi 4b); There i did the composer installation; Is there an extra cl for developer packages?

I wil do a fresh install then :)

**Comment by meijbaard** [comment]
> You are officially the first person external of the project to post an issue here! I didn't expect it at all 😄
> 
> Thanks for checking out the project.
> 
> Did `composer install` work well?

Yes, i had to manage some of the things my self. But finally i managed to get it installed. It then only did work if i activated it with the artisan command. That's why i moved to heroku to do a better check.

I saw some other (layout) issues already, i will post them here also. :)

**Comment by djaiss** [comment]
> I saw some other (layout) issues already, i will post them here also. :)

Please do! Any feedback is useful at this stage of the project.

**Comment by meijbaard** [comment]
I think it was the fact i run the composer install command with option --no-dev; Then it's obvious it won't work; After i did it again and removed the --no-dev input; faker was installed and ran properly;

**Comment by hashg** [comment]
I have tried the steps in [docs](https://docs.officelife.io/documentation/installation.html#installation-on-heroku) three times already on `Heroku`. Every time, I click "Deploy on Heroku".

1. Follow the documentation. 
   - Run `php artisan setup:dummyaccount`
   - `Error: Class "Faker\Factory" not found`
2. Follow the documentation. 
   - Run `composer install`
   - Run `php artisan setup:dummyaccount`
   - ERROR `Class "Faker\Factory" not found`
3. Follow the documentation. 
   - Before Heroku deploy. Set APP_ENV to  `local`
   - Run `composer install`
   - Run `php artisan setup:dummyaccount`
   - ERROR `Class "Faker\Factory" not found`

@meijbaard Please help me here.

**Comment by meijbaard** [comment]
Hi, yes running  `npm install` won't install everything you need I found out. You need to run `npm install dev` to install everything to setup the dummyaccount.

instead of setting up the dummyaccount, you can run `php artisan setup:production` this will setup an empty account. Open your app and when you have the emailsettings correct, you can login by creating a new account.

That last one I did on Heroku. On my own serve I did the install dev option. But there i can only access Officelife after `php artisan serve`

@hashg can you move forward with this?

**Comment by hashg** [comment]
@meijbaard Thanks for your info. I kept trying to get "dummyaccount" in heroku no luck so far. I've decided to install it locally on my machine. Please help me with high level commands to execute to get the full setup up and running locally?

**Comment by djaiss** [comment]
@hashg to set it up locally, it's pretty easy

`composer install`
`yarn install`
Then edit the `.env` file
then `php artisan setup:dummyaccount` to have a set of dummy data (if you run this, you can login with `admin@admin.com` and `admin`)

**Comment by meijbaard** [comment]
I think you will also need `yarn run dev `or `yarn run production`

Because without this i'm getting the screen below:
![Schermafbeelding 2021-05-05 om 10 44 16](https://user-images.githubusercontent.com/58352861/117116613-17b2a400-ad7e-11eb-974d-e9a6e44def9c.png)

**Comment by meijbaard** [comment]
Yeah, did the install again and with yarn run dev it worked properly, I also dit `php artisan lang:generate -vvv` and `php artisan lang:js -vvv` begore running `yarn run dev`

I ran into the issue that I needed to verify the email admin@admin.com, but managed this with setting a date in the approriate table/column within my database;

**Comment by meijbaard** [comment]
mmm. something to enthousiastic... when i selectd the company i'll get an 404 url not found issue. also get this error with the new monica 3.0 version, so i'm guessing i'm missing something here...

Just have to dive deeper into this... Let me know if you're getting any further @hashg

**Comment by djaiss** [comment]
I should definitely document all this because we didn't expect to have users at this stage of the project 😄

**Comment by meijbaard** [comment]
:D do you have any toughts on my 404 issue? Facing it with monca 3.0 and officelife now; Installed all the dependicies, but so far no luck...

**Comment by djaiss** [comment]
Are you using Docker or Homestead by any chance?

**Comment by meijbaard** [comment]
No just running apache local and installed it on an own server 😊
