### ISSUE TITLE
You can add multiple users with the same emailadress

### ISSUE THREAD

**Issue by meijbaard** [officelifehq/officelife#737]
I've addes several test users, als with the same emailadress and they are all added. You should expect that this would give an error, for every employee has his own/unique emailadd
![Schermafbeelding 2021-04-10 om 20 24 35](https://user-images.githubusercontent.com/58352861/114280774-7cead200-9a2a-11eb-891c-d333033f8886.png)
ress

**Comment by djaiss** [comment]
That should be the case though. In theory there is a check - so we might have a regression there. I'll make sure we'll fix this.
