### ISSUE TITLE
A new employee started this week and day is in the past should say something else

### ISSUE THREAD

**Issue by meijbaard** [officelifehq/officelife#738]
So an employee that is starting this week, but that day is not yet happend is fine... But the 9th is yesterday so I should expect that this would stated: Started instead of Starts
![Schermafbeelding 2021-04-10 om 20 30 36](https://user-images.githubusercontent.com/58352861/114280922-0c908080-9a2b-11eb-8bfd-4b88e78f3305.png)

**Comment by djaiss** [comment]
Nice catch! I didn't think of this. I'll fix it.
