### ISSUE TITLE
Bug: setup:dummyaccount - Faker\Factory not found

### ISSUE THREAD

**Issue by hashg** [officelifehq/officelife#788]
Deployed on Heroku. Executed scheduler. Then ran dummyaccount.
 
`php artisan setup:dummyaccount`

**Error**

This process will take a few minutes to complete. Be patient and read a book in the meantime.
[2021-04-18 20:46:58] production.ERROR: Class "Faker\Factory" not found {"exception":"[object] (Error(code: 0): Class \"Faker\\Factory\" not found at /app/app/Console/Commands/Tests/SetupDummyAccount.php:223)
[stacktrace]
#0 /app/app/Console/Commands/Tests/SetupDummyAccount.php(184): App\\Console\\Commands\\Tests\\SetupDummyAccount->start()
#1 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\Tests\\SetupDummyAccount->handle()
#2 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#6 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#7 /app/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#8 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#9 /app/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#10 /app/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /app/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#12 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#13 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#14 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 {main}
"} 

In SetupDummyAccount.php line 223:
                                   
  Class "Faker\Factory" not found

**Comment by djaiss** [comment]
Thanks @hashg for posting an issue here.

This is documented here: https://github.com/officelifehq/officelife/issues/722

This is because you ran `composer install --no-dev`. You need to run `composer install`.
