### ISSUE TITLE
Unable to visit /dashboard/me after first expense

### ISSUE THREAD

**Issue by hashg** [officelifehq/officelife#800]
- Deploy on heroku
- Do not load Dummy account
- Create your account now
- Create a company
- Goto /1/dashboard/me
- Create a expense
- Submit

Oops. An error occured.
Server Error

- Goto /1/dashboard/me

500 | Server Error

**Comment by djaiss** [comment]
Please enable `APP_DEBUG=true` in your env file, or check your logs, to understand why it crashes. 

It should work, obviously, so we need to figure out what's wrong.

**Comment by asbiin** [comment]
I found the error, and I'll fix it
