### ISSUE TITLE
Ability to have a knowledge base/wiki

### ISSUE THREAD

**Issue by cweagans** [officelifehq/officelife#917]
We have a number of policies, documents, checklists, etc. that we currently keep track of in a Google spreadsheet titled (and I'm not joking) the "Sheet of Sheets". It's literally a list of links to other spreadsheets and documents and such.

I would love to not have the Sheet of Sheets anymore.

To do that, we'd need some centralized place where we can either a) write a document/policy/etc directly, or b) link to an existing Google Doc or other external resource. It would be great if we could put it in some kind of organizational hierarchy in the wiki as well. For example, maybe there would be an "Accounting" section, which would link to budget spreadsheets, accounting processes, expense policies, etc. There might also be an "Engineering" section, which would link to the document describing how we work, code review policies, the SLA that we have in place for our products, etc.

To take this even further, it would be great if there were both a company-wide wiki and any number of smaller wikis that belonged to individual departments/business units. We have multiple business units that are doing very different things. Some documents (like our two factor authentication policy) apply business-wide, but some documents (like a proposal template that one business unit uses) aren't that useful to people that aren't working in that business unit.

**Comment by cweagans** [comment]
(another use case is compliance documentation -- if you're doing SOC2 or something similar, they usually require you to have written policies published somewhere that all employees can see them, along with requirements for regular review, updates, etc.)

**Comment by OrinSafko** [comment]
This would be incredible. I need a place where I can document for the team what we use each software for and why we decided on this software for this purpose. It would also be a place where we can provide instructions for new users on our team how we use each software. This would definitely fall in line with your vision for the Recruit domain, onboarding. Since software management is part of OfficeLife, this seems like a good way to tie this all together.

**Comment by djaiss** [comment]
@cweagans this is next on my todo list!

Thanks for submitting this idea.

**Comment by OrinSafko** [comment]
> @cweagans this is next on my todo list!
> 
> Thanks for submitting this idea.

Awesome! Can't wait for this.

**Comment by djaiss** [comment]
@cweagans @OrinSafko trying to scope the first iteration of this feature.

Should all wikis be public in the company for now?

**Comment by cweagans** [comment]
For the first iteration, certainly. Down the road, it might be nice to have e.g. an engineering wiki that is only accessible to an engineering team.

**Comment by djaiss** [comment]
> For the first iteration, certainly. Down the road, it might be nice to have e.g. an engineering wiki that is only accessible to an engineering team.

Makes sense!

**Comment by OrinSafko** [comment]
@djaiss I completely agree with @cweagans. Permissions aren't necessary for my team at the moment. But I could see it being necessary for some teams.

**Comment by djaiss** [comment]
The first iteration of the wiki is now in production. It's a bit rough for now, but we'll make it better over time 😄

**Comment by OrinSafko** [comment]
@djaiss this is excellent! This is a great start to being able to have our knowledgebase / documentation in OfficeLife. Thank you! I'll be putting feature requests for the Wiki in the discussions as I have ideas. Thanks!
