### ISSUE TITLE
Edit link email in profile not working

### ISSUE THREAD

**Issue by crishnakh** [officelifehq/officelife#986]
Hi, when I go to edit link (next email) in profile, it's not working, show an empty screen (white screen). 

Link example: https://beta.officelife.io/11/employees/45/edit 
![Captura de pantalla 2021-06-06 a las 23 31 27](https://user-images.githubusercontent.com/3185290/120940838-7b364580-c71f-11eb-99dd-b094661cddaf.png)

**Comment by djaiss** [comment]
Thanks so much @crishnakh for raising an issue.
It's indeed buggy in production and it's super weird because we don't have any errors.
I'll fix it as soon as possible.

**Comment by crishnakh** [comment]
Hi!
Now it's working!

**Comment by asbiin** [comment]
This has been fixed by #990
