### ISSUE TITLE
404 link error

### ISSUE THREAD

**Issue by crishnakh** [officelifehq/officelife#994]
When I clic on "Create a project" it's give me a 404 error
![Captura de pantalla 2021-06-07 a las 12 49 29](https://user-images.githubusercontent.com/3185290/121004384-ec611180-c78e-11eb-9f86-5902d0e72556.png)
![Captura de pantalla 2021-06-07 a las 12 49 34](https://user-images.githubusercontent.com/3185290/121004397-eec36b80-c78e-11eb-90ca-99dd05372b2c.png)

**Comment by djaiss** [comment]
Thanks a lot for caring enough to raise an issue. 

The fix has been created and will be soon in production and in a new release.
